### ISSUE TITLE
Secure WebSocket using wss

### ISSUE THREAD

**Issue by arun-gupta** [javaee-samples/javaee7-samples#119]

**Comment by cworsley4** [comment]
Question for you @arun-gupta, I have updated my web.xml file to match the one found in the endpoint-wss sample project but still have issue connecting over wss. Is there anymore direction you could provide in securing socket connections? My browser provides me with this status message: 
``WebSocket connection to *********** failed: Error in connection establishment: net::ERR_SSL_PROTOCOL_ERROR``

**Comment by arun-gupta** [comment]
What application server are you using?

**Comment by cworsley4** [comment]
Tomcat

**Comment by arun-gupta** [comment]
These samples are verified on a Java EE 7 compliant application server. You may like to ask your questions on Tomcat forum, OK?

**Comment by johnament** [comment]
Actually it looks like a bug with our own tests, @arun-gupta  and @rafabene .  If you look at https://github.com/javaee-samples/javaee7-samples/blob/master/websocket/endpoint-wss/src/main/webapp/websocket.js#L1 you're using the host portion not the host + port portion of the URL.  As a result it's going to assume 80 and 443.  The line below shows how to use it on 8080, but if you're running on most app servers the default https port will be 8443.  @cworsley4 you may want to give that a shot in your testing of it, comment out line 1, uncomment line 2 and replace 8080 with 8443 and see if that works.

**Comment by arun-gupta** [comment]
Always happy to take a PR :)
