### ISSUE TITLE
Create CI job for TravisCI

### ISSUE THREAD

**Issue by arun-gupta** [javaee-samples/javaee7-samples#206]
Alex Heusingfeld expressed interest in working on this.

**Comment by kubamarchwicki** [comment]
Wonder...

@johnament - any particular reason why tomee-embedded is the default profile for the travis build?
As it fails - it doesn't give a decent picture on PR.

I'd rather go for either 'safe profile'(like wildfly-embedded) or go for build matrix
```
env:
  matrix:
    - PROFILE=glassfish-embedded-arquillian
    - PROFILE=tomee-embedded-arquillian
    - PROFILE=wildfly-embedded-arquillian

script: "mvn clean install -P${PROFILE}"
```

or drop travis completely in favour of cloudbees and (maybe) https://wiki.jenkins-ci.org/display/JENKINS/GitHub+Plugin?

**Comment by arun-gupta** [comment]
+1 on wildfly-embedded, Tom EE is not Java EE 7 certified anyway.

**Comment by arjantijms** [comment]
We switched to travis quite some time ago, so this can be closed I think.
