### ISSUE TITLE
Add "jaspitest" security domain to standalone.xml of WildFly instances

### ISSUE THREAD

**Issue by arjantijms** [javaee-samples/javaee7-samples#243]
All JASPIC tests now fail because of a missing security domain. This security domain is a bit of an unfortunate thing (it actually shouldn't be needed, but for the moment it is)

The required XML to be added in the "security-domains" tag is:

```xml
<security-domain name="jaspitest" cache-type="default">
    <authentication-jaspi>
        <login-module-stack name="dummy">
            <login-module code="Dummy" flag="optional"/>
        </login-module-stack>
        <auth-module code="Dummy"/>
    </authentication-jaspi>
</security-domain>
```

**Comment by arjantijms** [comment]
It looks like this is still broken. See e.g.

https://javaee-support.ci.cloudbees.com/job/javaee7-samples-wildfly-8.2/lastBuild/org.javaee7.jaspic$wrapping/testReport/org.javaee7.jaspic.wrapping/WrappingTest/org_javaee7_jaspic_wrapping_WrappingTest/

Although WildFly is being more than a little cryptic with its error message, the following seems to indicate that the required security domain is still or again missing:

Caused by: java.lang.Exception: {"JBAS014771: Services with missing/unavailable dependencies" => ["jboss.undertow.deployment.default-server.default-host./3a7dd5d2-41ce-424c-8f03-a6ae390b9985.UndertowDeploymentInfoService is missing [jboss.security.security-domain.jaspitest]"]}

(btw, this also again proves how bad it is to *have* to rely on things in standalone.xml)

**Comment by arjantijms** [comment]
@johnament @arun-gupta Did you ever looked into this? Is it still broken or did it broke again when a new WildFly install was done?

**Comment by arun-gupta** [comment]
I never looked at it. Have you followed on wildfly-dev alias?

**Comment by arjantijms** [comment]
@arun-gupta 
>I never looked at it. Have you followed on wildfly-dev alias?

Sorry, I perhaps wasn't entirely clear. The question was not about fixing the underlying issue (I recently had a short discussion with Stefan Guilhen about this), but about applying the XML fragment from the openings post to standalone.xml.

But eventually this is probably not going to work. The JASPIC tests require a modification of standalone.xml, so I have to ask one of the maintainers of the WildFly installation of this project to do that. Maybe they do this, maybe they don't do this. Maybe my explanation is clear, maybe it isn't. And when the XML fragment gets applied, it may get put in the right or wrong place. And suppose it's finally at the right place, then everything starts all over again whenever a new installation for WildFly is done.

This is actually quite an interesting public display of exactly what goes wrong in organizations that have a split between developers and ops, and where something that is a developer thing has to be done by ops, since it's in a file that only ops is allowed to touch ;)

Perhaps its therefor better that we go for the solution proposed by @bartoszmajsak and pack a copy of standalone.xml with the tests where the fragment is added, or go for the CLI approach suggested by @radcortez. There's also some information here which mentions yet another method (programmatic): https://developer.jboss.org/thread/238534

**Comment by arun-gupta** [comment]
CLI approach is probably the recommended one. Do you think this needs further discussion or you can send a PR?

**Comment by arjantijms** [comment]
Okay, I'll try the CLI approach then. Don't think it needs much more discussion. I will experiment a bit with it locally and if works I'll send a PR. Thanks!

**Comment by trajano** [comment]
The CLI approach would be, but not sure where to put it in.

<pre>
/subsystem=security/security-domain=jaspitest:add(cache-type=default)
/subsystem=security/security-domain=jaspitest/authentication=jaspi:add()
/subsystem=security/security-domain=jaspitest/authentication=jaspi/login-module-stack=dummy:add()
/subsystem=security/security-domain=jaspitest/authentication=jaspi/login-module-stack=dummy/login-module=dummy:add(code=Dummy, flag=optional)
/subsystem=security/security-domain=jaspitest/authentication=jaspi/auth-module=jaspi:add(code=org.wildfly.extension.undertow.security.jaspi.modules.HTTPSchemeServerAuthModule, flag=required)
</pre>

**Comment by arjantijms** [comment]
I did a tiny amount of experimenting, but didn't got very far either with the CLI approach yet. It needs to be executed before the test war is deployed.

Another approach where I had more success with is a programmatic option. The code for that needs to be put in a jar and can be put in WEB-INF/lib (via e.g. Maven dependency). I was still contemplating how to handle this best. Publish the jar to Maven central and have the JBoss profile depend on it, or put the code in sub-module of the samples project.

**Comment by arjantijms** [comment]
With regards to the programmatic option mentioned in my last comment, I indeed published it to Maven central and wrote a blog article about it here: http://arjan-tijms.omnifaces.org/2015/08/activating-jaspic-in-jboss-wildfly.html

I'll look into adding this as a dependency for the current JASPIC tests to see if everything then runs on a stock JBoss.

**Comment by arjantijms** [comment]
Since WildFLy 10 and EAP 7.0 the jaspitest domain has been added by default, so this issue can be closed now.
