### ISSUE TITLE
SNAPSHOT build dependency missing.

### ISSUE THREAD

**Issue by whitingjr** [javaee-samples/javaee7-samples#283]
Hi,
 Tried for the first time building the ejb timer project by following the build instructions.

But getting this build error

> $ mvn -f ejb/timer/pom.xml package -DskipTests
> [INFO] Scanning for projects...
> [ERROR] The build could not read 1 project -> [Help 1]
> [ERROR]   
> [ERROR]   The project org.javaee7.ejb:timer:1.0-SNAPSHOT (/home/whitingjr/java/javaee7-samples/ejb/timer/pom.xml) has 1 error
> [ERROR]     Unresolveable build extension: Plugin org.codehaus.groovy:groovy-eclipse-compiler:2.8.0-01 or one of its dependencies could not be resolved: Could not find artifact org.codehaus.groovy:groovy-eclipse-batch:jar:2.3.4-01-SNAPSHOT -> [Help 2]
> [ERROR] 
> [ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
> [ERROR] Re-run Maven using the -X switch to enable full debug logging.
> [ERROR] 
> [ERROR] For more information about the errors and possible solutions, please read the following articles:
> [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException
> [ERROR] [Help 2] http://cwiki.apache.org/confluence/display/MAVEN/PluginResolutionException
> $

 Is there a repo I need to add to my settings.xml to resolve the snapshot version or something else ?

**Comment by akoblentz** [comment]
I'm having the same issue now... I've tried a few times.

**Comment by radcortez** [comment]
@whitingjr,

@akoblentz was having the same problem and after speaking with him, it was a problem in is local settings.xml that was pointing to a repo that didn't have the dependencies. Maybe you have a similar problem?

**Comment by kubamarchwicki** [comment]
On default (empty) settings.xml
```
{ /tmp }  » git clone git@github.com:javaee-samples/javaee7-samples.git
{ /tmp }  » cd javaee7-samples    
{ javaee7-samples } master » rm -rf ~/.m2/repository
{ javaee7-samples } master » mvn clean install -DskipTests  
   (...)
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 07:44 min

{ javaee7-samples } master » mvn package -f jaxrs/singleton/pom.xml -Pwildfly-remote-arquillian
   (...)
Results :

Tests run: 8, Failures: 0, Errors: 0, Skipped: 0

   (...)
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 17.390 s

```

Can we close the issue?

**Comment by radcortez** [comment]
I think so. Closing.
