### ISSUE TITLE
Missing artifact "test-utils" (run test for CDI)

### ISSUE THREAD

**Issue by olukashevich** [javaee-samples/javaee7-samples#293]
In https://nexus.codehaus.org/#view-repositories;snapshots~browsestorage~test there is no this artifact and maven can not run test for CDI - how can I fix it? 

Thanks.

**Comment by radcortez** [comment]
Go to this project: https://github.com/javaee-samples/javaee7-samples/tree/master/test-utils

And install it in your local repo with `mvn clean install`

**Comment by olukashevich** [comment]
Thanks!) I saw it 10 mins ago  herself)))))))))))

**Comment by radcortez** [comment]
Great! Fixed your problem?

**Comment by arun-gupta** [comment]
I thought we fixed it that anybody who build the workspace from scratch will not face this. Is this not the case?

**Comment by radcortez** [comment]
But you always need to perform the first build from the root folder.

**Comment by arun-gupta** [comment]
And then everything will work?

**Comment by radcortez** [comment]
Yes

**Comment by radcortez** [comment]
BTW, someone asked me and I've made this video explaining how to setup the samples:
https://www.youtube.com/watch?v=BB4b-Yz9cF0

**Comment by arun-gupta** [comment]
really nice, tweeted https://twitter.com/arungupta/status/573549034259943424

**Comment by olukashevich** [comment]
radcortez
"But you always need to perform the first build from the root folder."

Yes, I done it and can now running tests for CDI (i built exatly root folder, because test-utils has dependency on root artifact "samples-parent") - https://www.youtube.com/watch?v=BB4b-Yz9cF0 - like here.

Thank you very match!

**Comment by radcortez** [comment]
Thank you @arun-gupta 

You are welcome @olukashevich 

Closing this issue!
