### ISSUE TITLE
Remove groovy-eclipse-compiler dependency

### ISSUE THREAD

**Issue by mlabuda** [javaee-samples/javaee7-samples#308]
We, in JBDS, are trying to provide support for Java EE. One part includes importing, building and deploying websockets inside JBDS. Unfortunately this is not possible because there is no maven  groovy-eclipse-compiler connector for Eclipse Mars:
"No marketplace entries found to handle groovy-eclipse-compiler:2.8.0-01:add-groovy-build-paths in Eclipse. Please see Help for more information."

 groovy-eclipse-compiler is also a dependency for maven-compiler-plugin. It results to errors of invalid path (packages) - maven structure is not resolvable successfully what cause incapability of building and deploying a websockets project to a server. It is possible to delete errors from problems view and try to deploy it on your own, but m2e will result in not working deployment, see following examples:
* Building examples from command line and deploying on a server works.
* Building examples from IDE via maven (opened context menu of a project "Run As -> Maven Build" with build command "clean install") and marking created *.war as deployable + deploying on a server works.
* Building examples from IDE with m2e (drag and drop project on a server OR selecting and server and choosing a deployable content) does not work. This is caused bcs of not resolvable project structure bcs of issues with connectors.

**Comment by arun-gupta** [comment]
@mlabuda what is your proposal? i.e., what needs to be changed in existing project structure/pom.xml to simplify running these projects in JBDS?

**Comment by kubamarchwicki** [comment]
I think we've covered the scenarios in here https://github.com/javaee-samples/javaee7-samples/issues/291 - what's left is just a pull request... just ;-)

**Comment by arun-gupta** [comment]
@mlabuda can you send a PR then? :)

**Comment by mlabuda** [comment]
It's not so simple as kuba said here https://github.com/javaee-samples/javaee7-samples/issues/291#issuecomment-77557570 

Removing it only from maven-compiler-plugin dependencies and configuration makes mvn build failing.
Could you please look at it? Thanks.

**Comment by bartoszmajsak** [comment]
What is the exact reason of failing build? Because the build is failing by default when running tests anyway ;)

**Comment by mlabuda** [comment]
"[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:testCompile (default-testCompile) on project jsf-bean-validation: Compilation failure
[ERROR] /home/equo/testing/java-ee7-samples/javaee7-samples/jsf/bean-validation/src/test/java/org/javaee7/jsf/bean/validation/MyBeanTest.java:[66,22] cannot access org.w3c.dom.ElementTraversal
[ERROR] class file for org.w3c.dom.ElementTraversal not found."

Before removing only groovy eclipse compiler from maven compiler plugin it worked. I am not running tests. Building is performed with goal "clean install -DskipTests"

**Comment by kubamarchwicki** [comment]
Please have a look if this PR #310 works for you. 
There is no Groovy / Spock  dependecy unless you build the `extra` module explicitly.

Your error seem to me quite suspicious though and might not be related to groovy itself.
