### ISSUE TITLE
jpa/schema-gen-script-generate

### ISSUE THREAD

**Issue by AndreaGencova** [javaee-samples/javaee7-samples#316]
change of project directory.

**Comment by arun-gupta** [comment]
Can you describe the issue?

**Comment by AndreaGencova** [comment]
In this module were used linux directory in persistence.xml (file:tmp/...), in test also.
I'm windows user so  I couldn't build the project. We fixed it to a relative path, project buil directory usage.  We ran test as client, on the client side.

**Comment by arun-gupta** [comment]
Have you tested on Windows, Linux, and Mac?

**Comment by AndreaGencova** [comment]
no, just Windows.

**Comment by arun-gupta** [comment]
PR can be merged after its checked on at least one variety of Linux. Can you try it?

**Comment by AndreaGencova** [comment]
This version of PR sucessfully passes on Mac and WildFly.
