### ISSUE TITLE
Can the DataStax Java Driver (Cassandra) be safely used in EE servers?

### ISSUE THREAD

**Issue by marlonpatrick10** [javaee-samples/javaee7-samples#323]
Hi everyone,

I saw that there is an example of integration with Cassandra using the DataStax driver but I wonder if in a production environment the presented approach can be valid.

From what I could see from code example of javaee7-samples and the answers in the group-list of DataStax Java Driver (https://groups.google.com/a/lists.datastax.com/forum/#!forum/java-driver-user) my findings until the moment are:
- The driver does not hurt the EJB specification and can use it within an EJB normally;
- Although not hurt the EJB specification, there is no official API/standardized/widely used in which the Java EE Server can manage connections of a Cassandra cluster;
- Can I create a Cluster/Session objects within a javax.ejb.Singleton to facilitate the implementation of the four rules for using Cassandra driver (http://www.datastax.com/dev/blog/4-simple-rules-when-using-the-datastax-drivers-for-cassandra);
- Could take advantage of some features of EJB as concurrency control and dependency injection with CDI, however, other features like transaction management lose all sense;

I am currently seeking this information because I am doing a small application to learn Cassandra, and I'll try this javaee7-sample approach.

But the question remains that: In a production environment, you see this attempt at integration as something plausible?

**Comment by arjantijms** [comment]
Moved to extra project
