### ISSUE TITLE
Test jms/* fail in Weblogic 12.1.3

### ISSUE THREAD

**Issue by joedayz** [javaee-samples/javaee7-samples#346]
Now, trying jms in weblogic 12.1.3 

$ mvn clean install -Pweblogic-remote-arquillian -DweblogicRemoteArquillian_wlHome=C:\Tools\wls12130

Error:

Tests in error:
  org.javaee7.jms.send.receive.mdb.AsyncTest: Deployment Failed on server: com.bea.xml.XmlException: failed to load java type corresponding to e=ejb-jar@http://xmlns.jcp.org/xml/ns/javaee
  org.javaee7.jms.send.receive.SyncTest: Deployment Failed on server: java.lang.ClassNotFoundException: javax.jms.JMSContext

Any idea?

Joe

**Comment by arjantijms** [comment]
The exception is expected. `javax.jms.JMSContext` is a JMS 2.0/Java EE 7 type, it wasn't present in JMS 1.1/Java EE 6.

WebLogic 12.1.3 is a Java EE 6 implementation, so it should indeed fail.

WebLogic 12.2.1 is a Java EE 7 implementation, and it should work (if it would fail in 12.2.1 as well it may be an implementation bug)

**Comment by johnament** [comment]
Closing out, based on arjan's comments.

**Comment by rosiecki** [comment]
Hi, I was looking for some stuff on the web and found this, you're gonna like it, just take a look here <http://dyciprele.narmaonline.org/aehdfmq>

Good wishes, metempsychoza@wp.pl
