### ISSUE TITLE
AngularJS example assumes JBoss runtime

### ISSUE THREAD

**Issue by johnament** [javaee-samples/javaee7-samples#349]
The angular example is assuming that its running on JBoss.

Persistence.xml refers to the jboss namespace: https://github.com/javaee-samples/javaee7-samples/blob/master/jaxrs/angularjs/src/main/resources/META-INF/persistence.xml#L6 and is pointing to the hibernate specific DDL properties.

Uses HQL instead of JPQL: https://github.com/javaee-samples/javaee7-samples/blob/master/jaxrs/angularjs/src/main/java/com/example/rest/NoteResourceImpl.java#L20

**Comment by arjantijms** [comment]
I'm tempted to move this sample to the extra folder. That doesn't fix the fact that it's JBoss specific, but I think it fits better there. Perhaps it would be even better to create a completely separate project for that even.

Sorry for going offtopic here ;)

**Comment by arjantijms** [comment]
AngularJS was moved to the new extras project
