### ISSUE TITLE
[Question] BUILD FAILURE - how to run success?

### ISSUE THREAD

**Issue by donhuvy** [javaee-samples/javaee7-samples#357]
I follow this video tutorial: https://www.youtube.com/watch?v=BB4b-Yz9cF0
```
mvn clean install -Dmaven.test.skip=true

cd jpa
cd native-sql
cd native-sql-resultset-mapping

mvn clean install -Pwildfly-embedded-arquillian
```
but not success. I stuck at here and can't overcome. The below is terminal screen, please help me! (Because terminal screen text is too long, I must paste it to Gist)

https://gist.github.com/donhuvy/2e91ca8924de0f739121b0b4100af579

Thank you!

<img width="1440" alt="screen shot 2016-07-24 at 4 31 42 pm" src="https://cloud.githubusercontent.com/assets/1328316/17083021/4a90bfd8-51bc-11e6-939b-88adc9452755.png">

**Comment by donhuvy** [comment]
```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-dependency-plugin:2.8:unpack (unpack) on project jpa-native-sql: Unable to resolve artifact. Could not transfer artifact org.wildfly:wildfly-dist:zip:8.2.0.Final from/to central (https://repo.maven.apache.org/maven2): GET request of: org/wildfly/wildfly-dist/8.2.0.Final/wildfly-dist-8.2.0.Final.zip from central failed
```

**Comment by arjantijms** [comment]
Looks like some problem related to reaching maven central, as the wildfly 8.2 artefact at https://repo.maven.apache.org/maven2/org/wildfly/wildfly-dist/8.2.0.Final/ seems to be there.

Alternatively you could try to use some of the other "embedded" profiles such as

``mvn clean test -Pwildfly-managed-arquillian``

or

``mvn clean test -Ptomee-managed-arquillian``

or

``mvn clean test -Pliberty-embedded-arquillian``

Yet another alternative is to start up your own external WildFly separately and then use

``mvn clean test -Pwildfly-remote-arquillian``

**Comment by donhuvy** [comment]
Thank you! I run
```
mvn clean test -Pwildfly-managed-arquillian
```
and success.
