### ISSUE TITLE
Move extra module to separate project?

### ISSUE THREAD

**Issue by arjantijms** [javaee-samples/javaee7-samples#369]
The extra module is currently commented out, but still part of this project.

Since Java EE 7 samples is already unwieldy and huge, I think it's better to move this to a separate top-level project, e.g.  `javaee-samples-extra`.

That project can then focus on integration of Java EE with a large variety of external projects, from Quartz, to OmniFaces (wink wink ;)), to AngularJS and everything in between. Tests can then also be written using any kind of testing framework and any language (Groovy, Scala, Kotlin, JavaScript, ... whatever someone comes up with).

Thoughts?

**Comment by radcortez** [comment]
+1

I'm not so sure if just an extra project should be the right way to go. It might became a big garbage bag. Maybe have dedicated extra projects to each technology? Java EE + Angular, Java EE + Spring, etc.

**Comment by arjantijms** [comment]
Did the initial step by moving to a new project. Further splitting it out depends on the interest in this new project.
