### ISSUE TITLE
How-To replace RestEasy with Jersey in WildFly

### ISSUE THREAD

**Issue by noahwhite** [javaee-samples/javaee7-samples#93]
Similar to #92 a How-To that explains replacing RestEasy with Jersey in WildFly would be useful. I wonder what implications this would have on any RestEasy usage that might be part of the WildFly administration console. I think it's nearly impossible to switch JAX-RS impls. in Glassfish for this reason, but I could be mistaken. If its not possible to replace at the AS level then a sample showing its usage in a WAR and EAR would be useful.

**Comment by oluwasayo** [comment]
@arun-gupta I think WADL publishing (just like the WSDL for jax-ws) is a good enough reason. That's what led me here from Google Search. I've seen the Maven Jersey plugging that does this at build time but I think that's not good enough. Besides, my project uses Ant. 
Any help?

**Comment by arun-gupta** [comment]
Closing this issue, please open a new issue for this or discuss in Jersey list.
